from selenium.webdriver.common.by import By

class OrderPageLocators:
    title_page_personal = (By.XPATH, "//div[text()='Для кого самокат' and contains(@class, 'Order_Header')]")
    name = (By.XPATH, "//input[@placeholder='* Имя']")
    lastname = (By.XPATH, "//input[@placeholder='* Фамилия']")
    address = (By.XPATH, "//input[@placeholder='* Адрес: куда привезти заказ']")
    metro = (By.XPATH, "//input[@placeholder='* Станция метро']")
    select_dropdown_metro = (By.XPATH, "//li[@class='select-search__row']")
    phone = (By.XPATH, "//input[@placeholder='* Телефон: на него позвонит курьер']")
    button_next = (By.XPATH, "//button[@class='Button_Button__ra12g Button_Middle__1CSJM']")
    title_rent_page = (By.XPATH, "//div[text()='Про аренду' and contains (@class, 'Order_Header')]")
    date = (By.XPATH, "//input[@placeholder='* Когда привезти самокат']")
    date_in_focus = (By.XPATH, "//div[@class = 'react-datepicker__tab-loop']")
    calendar = (By.XPATH, "//div[@class='react-datepicker-popper']")
    calendar_item = (By.XPATH, "//div[contains(@class, 'react-datepicker__day') and contains(@tabindex, '0')]")
    rental_period = (By.XPATH, "//div[text()='* Срок аренды']")
    dropdown_rental_period = (By.XPATH, "//div[@class = 'Dropdown-menu']/div[text()= 'трое суток']")
    checkbox_grey_color = (By.XPATH, "//input[@id= 'grey']")
    comment = (By.XPATH, "//input[@placeholder='Комментарий для курьера']")
    button_make_order = (By.XPATH, "//div[contains(@class, 'Order_Buttons')]/button[text()='Заказать']")
    button_confirm_order = (By.XPATH, "//button[text()='Да']")
    title_successful_order = (By.XPATH, "//div[text()='Заказ оформлен']")
    button_Check_status = (By.XPATH, ".//*[text()='Посмотреть статус']")
    header_logo_scooter = (By.CLASS_NAME, "Header_LogoScooter__3lsAR")
    header_logo_yandex = (By.CLASS_NAME, "Header_LogoYandex__3TSOI")
